#!/bin/env python3

import pandas
import random
import string
import sys

all_posters = [
    "".join(random.choice(string.ascii_letters) for _ in range(8)) for _ in range(120)
]

all_graders = [
    "".join(random.choice(string.ascii_letters) for _ in range(8)) for _ in range(40)
]

df = pandas.DataFrame(columns=["Poster", "Grader1", "Grade1", "Grader2", "Grade2"])

for poster in all_posters:
    chosen_graders = random.sample(all_graders, 2)
    have_second_grader = random.random() > 0.1
    df = pandas.concat(
        [
            df,
            pandas.DataFrame(
                {
                    "Poster": [poster],
                    "Grader1": [chosen_graders[0]],
                    "Grade1": [random.randint(0, 10)],
                    "Grader2": [chosen_graders[1] if have_second_grader else None],
                    "Grade2": [random.randint(0, 10) if have_second_grader else None],
                }
            ),
        ],
        ignore_index=True,
    )

df.to_excel(sys.argv[1], index=False)
